package com.cn.mybatis.generator;


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.Set;

import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.InnerEnum;
import org.mybatis.generator.api.dom.java.JavaElement;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.api.dom.java.TopLevelClass;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.config.PropertyRegistry;
import org.mybatis.generator.internal.util.StringUtility;

/**
 * 修改Mybatis Generator 生成的所有注释的文档
 *
 * @author wl
 */
public class MyCommentGenerator implements CommentGenerator {



    /**
     * Instantiates a new default comment generator.
     */
    public MyCommentGenerator() {
        super();

    }

    /* java文件最上面，package上面得注释
     * (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addJavaFileComment(org.mybatis.generator.api.dom.java.CompilationUnit)
     */
    @Override
    public void addJavaFileComment(final CompilationUnit compilationUnit) {

    }

    /**
     * Adds a suitable comment to warn users that the element was generated, and when it was generated.
     *
     * @param xmlElement
     *            the xml element
     */
    @Override
    public void addComment(final XmlElement xmlElement) {

        xmlElement.addElement(new TextElement("<!-- addComment")); //$NON-NLS-1$

//        final StringBuilder sb = new StringBuilder();
//        sb.append(MergeConstants.NEW_ELEMENT_TAG+" ++++++");
//        xmlElement.addElement(new TextElement(sb.toString()));

        xmlElement.addElement(new TextElement("-->")); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addRootComment(org.mybatis.generator.api.dom.xml.XmlElement)
     */
    @Override
    public void addRootComment(final XmlElement rootElement) {
        // add no document level comments by default
    	rootElement.addElement(new TextElement("<!-- addRootComment-->"));
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addConfigurationProperties(java.util.Properties)
     */
    @Override
    public void addConfigurationProperties(final Properties properties) {

    }

       public static boolean isTrue(String s) {
            return "true".equalsIgnoreCase(s); //$NON-NLS-1$
       }

    /**
     * This method adds the custom javadoc tag for. You may do nothing if you do not wish to include the Javadoc tag -
     * however, if you do not include the Javadoc tag then the Java merge capability of the eclipse plugin will break.
     *
     * @param javaElement
     *            the java element
     * @param markAsDoNotDelete
     *            the mark as do not delete
     */

    /**
     * This method returns a formated date string to include in the Javadoc tag
     * and XML comments. You may return null if you do not want the date in
     * these documentation elements.
     * 
     * @return a string representing the current timestamp, or null
     */
    protected String getDateString() {

            return new Date().toString();
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addClassComment(org.mybatis.generator.api.dom.java.InnerClass, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public void addClassComment(final InnerClass innerClass,
            final IntrospectedTable introspectedTable) {

        final StringBuilder sb = new StringBuilder();

        innerClass.addJavaDocLine("/** addClassComment"); //$NON-NLS-1$
//        innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator."); //$NON-NLS-1$
//
//        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
//        sb.append(introspectedTable.getFullyQualifiedTable());
//        innerClass.addJavaDocLine(sb.toString());

        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addTopLevelClassComment(org.mybatis.generator.api.dom.java.TopLevelClass, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public void addModelClassComment(final TopLevelClass topLevelClass,
            final IntrospectedTable introspectedTable) {

        final StringBuilder sb = new StringBuilder();

        topLevelClass.addJavaDocLine("/** addModelClassComment"); //$NON-NLS-1$
//
//        final String remarks = introspectedTable.getRemarks();
//        if (addRemarkComments && StringUtility.stringHasValue(remarks)) {
//            topLevelClass.addJavaDocLine(" * Database Table Remarks:");
//            final String[] remarkLines = remarks.split(System.getProperty("line.separator"));  //$NON-NLS-1$
//            for (String remarkLine : remarkLines) {
//                topLevelClass.addJavaDocLine(" *   " + remarkLine);  //$NON-NLS-1$
//            }
//        }
////        topLevelClass.addJavaDocLine(" *"); //$NON-NLS-1$
//
////        topLevelClass
////                .addJavaDocLine(" * This class was generated by MyBatis Generator."); //$NON-NLS-1$
//
////        sb.append(" * This class corresponds to the database table "); //$NON-NLS-1$
//        sb.append(" * tablename  "); //$NON-NLS-1$
//        sb.append(introspectedTable.getFullyQualifiedTable());
//        topLevelClass.addJavaDocLine(sb.toString());

        topLevelClass.addJavaDocLine(" * @auth " + "aut");
        topLevelClass.addJavaDocLine(" * @date " + getDateString());
        topLevelClass.addJavaDocLine(" * @version " + "1.0");
        topLevelClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addEnumComment(org.mybatis.generator.api.dom.java.InnerEnum, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public void addEnumComment(final InnerEnum innerEnum,
            final IntrospectedTable introspectedTable) {

//        StringBuilder sb = new StringBuilder();

        innerEnum.addJavaDocLine("/** addEnumComment"); //$NON-NLS-1$
        innerEnum.addJavaDocLine(" *===========addEnumComment=============/");
        innerEnum.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addFieldComment(org.mybatis.generator.api.dom.java.Field, org.mybatis.generator.api.IntrospectedTable, org.mybatis.generator.api.IntrospectedColumn)
     */
    @Override
    public void addFieldComment(final Field field,
            final IntrospectedTable introspectedTable,
            final IntrospectedColumn introspectedColumn) {

        field.addJavaDocLine("/** addFieldComment 2"); //$NON-NLS-1$


        field.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addFieldComment(org.mybatis.generator.api.dom.java.Field, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public void addFieldComment(final Field field, final IntrospectedTable introspectedTable) {

        field.addJavaDocLine("/** addFieldComment 3"); //$NON-NLS-1$

        field.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addGeneralMethodComment(org.mybatis.generator.api.dom.java.Method, org.mybatis.generator.api.IntrospectedTable)
     */
    @Override
    public void addGeneralMethodComment(final Method method,
            final IntrospectedTable introspectedTable) {

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/** addGeneralMethodComment"); //$NON-NLS-1$

//        List<Parameter> parameters =  method.getParameters();
//        
//        for (Parameter parameter : parameters) {
//            sb.append(" *@param  ");
//            sb.append(parameter.getName());
//            sb.append(".");
//            method.addJavaDocLine(sb.toString());
//            sb.delete(0, sb.length());
//        }
//        method.addJavaDocLine(method.getReturnType()==null || method.getReturnType().getShortName()==null ? ""
//                :" *@return "+method.getReturnType().getShortName()+".");

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addGetterComment(org.mybatis.generator.api.dom.java.Method, org.mybatis.generator.api.IntrospectedTable, org.mybatis.generator.api.IntrospectedColumn)
     */
    @Override
    public void addGetterComment(final Method method,
            final IntrospectedTable introspectedTable,
            final IntrospectedColumn introspectedColumn) {

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/** addGetterComment"); //$NON-NLS-1$
//
//        sb.append(" * @return "+(
//                introspectedColumn.getActualColumnName()==null ? "":introspectedColumn.getActualColumnName()));
//        sb.append(" .");
//        method.addJavaDocLine(sb.toString());

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addSetterComment(org.mybatis.generator.api.dom.java.Method, org.mybatis.generator.api.IntrospectedTable, org.mybatis.generator.api.IntrospectedColumn)
     */
    @Override
    public void addSetterComment(final Method method,
            final IntrospectedTable introspectedTable,
            final IntrospectedColumn introspectedColumn) {

        StringBuilder sb = new StringBuilder();

        method.addJavaDocLine("/** addSetterComment"); //$NON-NLS-1$
//        Parameter parm = method.getParameters().get(0);
//        sb.setLength(0);
//        sb.append(" * @param "); //$NON-NLS-1$
//        sb.append(parm.getName());
//        sb.append((introspectedColumn.getRemarks()==null ? " " : "  "+introspectedColumn.getRemarks()));
//        sb.append(".");
//        method.addJavaDocLine(sb.toString());

        method.addJavaDocLine(" */"); //$NON-NLS-1$
    }

    /* (non-Javadoc)
     * @see org.mybatis.generator.api.CommentGenerator#addClassComment(org.mybatis.generator.api.dom.java.InnerClass, org.mybatis.generator.api.IntrospectedTable, boolean)
     */
    @Override
    public void addClassComment(final InnerClass innerClass,
            final IntrospectedTable introspectedTable, final boolean markAsDoNotDelete) {
        final StringBuilder sb = new StringBuilder();

        innerClass.addJavaDocLine("/** addClassComment"); //$NON-NLS-1$


        innerClass.addJavaDocLine(" */"); //$NON-NLS-1$
    }

	@Override
	public void addGeneralMethodAnnotation(Method method, IntrospectedTable introspectedTable,
			Set<FullyQualifiedJavaType> imports) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void addGeneralMethodAnnotation(Method method, IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn, Set<FullyQualifiedJavaType> imports) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void addFieldAnnotation(Field field, IntrospectedTable introspectedTable,
			Set<FullyQualifiedJavaType> imports) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void addFieldAnnotation(Field field, IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn, Set<FullyQualifiedJavaType> imports) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void addClassAnnotation(InnerClass innerClass, IntrospectedTable introspectedTable,
			Set<FullyQualifiedJavaType> imports) {
		// TODO Auto-generated method stub
		
	}
}
